#!/usr/bin/env python3
"""Project directory utilities for digitus-Dei."""

import json
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

from registry import Project, get_projects_dir


def slugify(title: str) -> str:
    """Convert title to URL-safe slug."""
    slug = title.lower()
    slug = re.sub(r"[^a-z0-9\s_-]", "", slug)
    slug = re.sub(r"[\s_]+", "-", slug)
    slug = re.sub(r"-+", "-", slug)
    return slug.strip("-")[:50]


def get_unique_project_dir(slug: str, projects_dir: Path) -> Path:
    """Get a unique project directory, appending counter if needed."""
    base = projects_dir / slug
    if not base.exists():
        return base
    for i in range(2, 100):
        candidate = projects_dir / f"{slug}-{i}"
        if not candidate.exists():
            return candidate
    raise ValueError(f"Too many projects with slug '{slug}'")


def init_project_dir(project: Project, projects_dir: Path) -> Path:
    """Create project directory structure."""
    slug = slugify(project.title)
    project_dir = get_unique_project_dir(slug, projects_dir)

    project_dir.mkdir(parents=True, exist_ok=True)
    (project_dir / "src").mkdir(exist_ok=True)
    (project_dir / "tests").mkdir(exist_ok=True)

    readme_content = f"""# {project.title}

## Overview

{project.spec}

## Tech Stack

{chr(10).join(f"- {tech}" for tech in project.tech_stack)}

## Status

- **Created:** {project.created_at}
- **Priority:** Urgency {project.priority.urgency}/4, Difficulty {project.priority.difficulty}/4

## Original Brief

> {project.brief}

---

*Generated by digitus-Dei*
"""
    (project_dir / "README.md").write_text(readme_content)

    design_content = f"""# Design Decisions

## {datetime.now(timezone.utc).strftime("%Y-%m-%d")} - Project Initialized

Project created from brief: "{project.brief}"

### Initial Architecture

(To be filled by executing agent)

---

*Append new decisions below this line*
"""
    (project_dir / "DESIGN.md").write_text(design_content)

    changelog_content = f"""# Changelog

## {datetime.now(timezone.utc).strftime("%Y-%m-%d")} - Project Created

- Initial project structure generated
- README.md with specification
- DESIGN.md initialized

---

*Append new entries below this line*
"""
    (project_dir / "CHANGELOG.md").write_text(changelog_content)

    return project_dir


def create_blocker(project_dir: Path, reason: str) -> Path:
    """Create blocker.md file."""
    blocker_path = project_dir / "blocker.md"
    content = f"""# Blocker

**Created:** {datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")}

## Issue Description

{reason}

## Context

(Add relevant context, error messages, logs)

## Attempted Solutions

(Document what was tried)

## Questions for User

(What information is needed to unblock?)
"""
    blocker_path.write_text(content)
    return blocker_path


def remove_blocker(project_dir: Path) -> bool:
    """Remove blocker.md file."""
    blocker_path = project_dir / "blocker.md"
    if blocker_path.exists():
        blocker_path.unlink()
        return True
    return False


def create_wrap_up(project_dir: Path, summary: str) -> Path:
    """Create wrap-up file for paused project."""
    wrap_up_dir = project_dir / "wrap-up"
    wrap_up_dir.mkdir(exist_ok=True)

    now = datetime.now(timezone.utc)
    timestamp = now.strftime("%Y-%m-%d-%H%M%S")
    date_display = now.strftime("%Y-%m-%d %H:%M UTC")
    wrap_up_path = wrap_up_dir / f"{timestamp}.md"

    content = f"""# Wrap-Up: {date_display}

## Summary

{summary}

## Work Completed

(List of completed tasks)

## In Progress

(What was being worked on)

## Next Steps

(What should be done next)

## Notes

(Any additional context for resumption)
"""
    wrap_up_path.write_text(content)
    return wrap_up_path


def get_latest_wrap_up(project_dir: Path) -> str | None:
    """Get content of most recent wrap-up file."""
    wrap_up_dir = project_dir / "wrap-up"
    if not wrap_up_dir.exists():
        return None

    files = sorted(wrap_up_dir.glob("*.md"), reverse=True)
    if not files:
        return None

    return files[0].read_text()


def get_blocker_content(project_dir: Path) -> str | None:
    """Get content of blocker.md if it exists."""
    blocker_path = project_dir / "blocker.md"
    if blocker_path.exists():
        return blocker_path.read_text()
    return None


def init_git_repo(project_dir: Path) -> bool:
    """Initialize git repository."""
    try:
        subprocess.run(
            ["git", "init"],
            cwd=project_dir,
            check=True,
            capture_output=True,
        )

        gitignore = """# Python
__pycache__/
*.py[cod]
.venv/
venv/
.tox/

# IDE
.idea/
.vscode/
*.swp

# OS
.DS_Store
Thumbs.db

# Project
.digitus-registry.json
"""
        (project_dir / ".gitignore").write_text(gitignore)

        subprocess.run(
            ["git", "add", "."],
            cwd=project_dir,
            check=True,
            capture_output=True,
        )
        subprocess.run(
            ["git", "commit", "-m", "Initial commit - project scaffolding"],
            cwd=project_dir,
            check=True,
            capture_output=True,
        )
        return True
    except subprocess.CalledProcessError:
        return False


def create_github_repo(project_dir: Path) -> str | None:
    """Create private GitHub repository and push."""
    try:
        slug = project_dir.name
        result = subprocess.run(
            ["gh", "repo", "create", slug, "--private", "--source=.", "--push"],
            cwd=project_dir,
            check=True,
            capture_output=True,
            text=True,
        )
        for line in result.stdout.split("\n") + result.stderr.split("\n"):
            if "github.com" in line:
                return line.strip()

        result = subprocess.run(
            ["gh", "repo", "view", "--json", "url", "-q", ".url"],
            cwd=project_dir,
            check=True,
            capture_output=True,
            text=True,
        )
        return result.stdout.strip()
    except subprocess.CalledProcessError:
        return None


def get_project_dir(project: Project, projects_dir: Path) -> Path:
    """Get project directory path from project.

    Searches for existing directory matching the slug pattern (slug, slug-2, etc.)
    since init_project_dir may have created a numbered variant on collision.
    """
    slug = slugify(project.title)
    base = projects_dir / slug
    if base.exists():
        return base
    # Check for numbered variants created by get_unique_project_dir
    for i in range(2, 100):
        candidate = projects_dir / f"{slug}-{i}"
        if candidate.exists():
            return candidate
    # Fallback to base slug (directory may not exist yet)
    return base


def main() -> None:
    if len(sys.argv) < 2:
        print("Usage: project_utils.py <command> [args]")
        print("Commands: init, blocker, wrap-up, get-wrap-up, get-blocker")
        sys.exit(1)

    cmd = sys.argv[1]

    if cmd == "init":
        projects_dir = get_projects_dir()
        project_data = json.loads(sys.stdin.read())
        project = Project.from_dict(project_data)
        project_dir = init_project_dir(project, projects_dir)
        init_git_repo(project_dir)
        print(str(project_dir))

    elif cmd == "github":
        if len(sys.argv) < 3:
            print("Usage: project_utils.py github <project_dir>")
            sys.exit(1)
        project_dir = Path(sys.argv[2])
        url = create_github_repo(project_dir)
        if url:
            print(url)
        else:
            sys.exit(1)

    elif cmd == "blocker":
        if len(sys.argv) < 3:
            print("Usage: project_utils.py blocker <project_dir> < reason")
            sys.exit(1)
        project_dir = Path(sys.argv[2])
        reason = sys.stdin.read()
        path = create_blocker(project_dir, reason)
        print(str(path))

    elif cmd == "remove-blocker":
        if len(sys.argv) < 3:
            print("Usage: project_utils.py remove-blocker <project_dir>")
            sys.exit(1)
        project_dir = Path(sys.argv[2])
        if remove_blocker(project_dir):
            print("Removed")
        else:
            print("No blocker found")

    elif cmd == "wrap-up":
        if len(sys.argv) < 3:
            print("Usage: project_utils.py wrap-up <project_dir> < summary")
            sys.exit(1)
        project_dir = Path(sys.argv[2])
        summary = sys.stdin.read()
        path = create_wrap_up(project_dir, summary)
        print(str(path))

    elif cmd == "get-wrap-up":
        if len(sys.argv) < 3:
            print("Usage: project_utils.py get-wrap-up <project_dir>")
            sys.exit(1)
        project_dir = Path(sys.argv[2])
        content = get_latest_wrap_up(project_dir)
        if content:
            print(content)
        else:
            sys.exit(1)

    elif cmd == "get-blocker":
        if len(sys.argv) < 3:
            print("Usage: project_utils.py get-blocker <project_dir>")
            sys.exit(1)
        project_dir = Path(sys.argv[2])
        content = get_blocker_content(project_dir)
        if content:
            print(content)
        else:
            sys.exit(1)

    elif cmd == "slugify":
        if len(sys.argv) < 3:
            print("Usage: project_utils.py slugify <title>")
            sys.exit(1)
        print(slugify(sys.argv[2]))

    else:
        print(f"Unknown command: {cmd}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
